name: Unlighthouse Audit
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Activacion manual 
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Unlighthouse
        run: npm install -g unlighthouse

      - name: Run Unlighthouse
        run: unlighthouse ci --site https://ulp.ugr.es --site-key ulp-ugr --budget '{"performance":90,"accessibility":90,"best-practices":90,"seo":90}'
        # en el budget he definido los valores que considero aceptables para cada uno de los aspectos que se puede medir
        # los valores que yo es puesto son completamente subjetivos, y he puesto 90 porque me ha dado la gana jaja

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unlighthouse-report
          path: .unlighthouse
